# Generated by Django 5.0.6 on 2024-06-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
