# Generated by Django 5.0.6 on 2024-06-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_favorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="product",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
