# Generated by Django 5.0.6 on 2024-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
